apiVersion: v2
name: couchpotato
description: Automatic Movie Downloading via NZBs & Torrents
icon: https://avatars3.githubusercontent.com/u/25025331?s=400&v=4
home: https://github.com/kindred/k8s-usenet/tree/master/couchpotato
keywords:
  - couchpotato
  - usenet
  - bittorrent
sources:
  - https://hub.docker.com/r/linuxserver/couchpotato/
  - https://github.com/couchpotato/couchpotato/
  
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: amd64-latest
