apiVersion: v1
entries:
  bazarr:
  - apiVersion: v2
    appVersion: amd64-latest
    created: "2023-01-08T20:09:33.061213506+11:00"
    description: Bazarr is a companion application to Sonarr and Radarr. It manages
      and downloads subtitles based on your requirements.
    digest: 13a337fee781ef27c2e4032c503f0d72a7202d154854ad0751be988d67232768
    home: https://github.com/kindred/k8s-usenet/tree/master/bazarr
    icon: https://www.bazarr.media/assets/img/logo.png
    keywords:
    - bazarr
    - usenet
    - bittorrent
    name: bazarr
    sources:
    - https://hub.docker.com/r/linuxserver/bazarr/
    - https://github.com/morpheus65535/bazarr
    type: application
    urls:
    - bazarr-1.0.0.tgz
    version: 1.0.0
  couchpotato:
  - apiVersion: v2
    appVersion: amd64-latest
    created: "2023-01-08T20:09:33.062489104+11:00"
    description: Automatic Movie Downloading via NZBs & Torrents
    digest: 0c36e39eafff5d26b312aba0be8d2f60dce06beb047dcb8202eacdacf61be4f1
    home: https://github.com/kindred/k8s-usenet/tree/master/couchpotato
    icon: https://avatars3.githubusercontent.com/u/25025331?s=400&v=4
    keywords:
    - couchpotato
    - usenet
    - bittorrent
    name: couchpotato
    sources:
    - https://hub.docker.com/r/linuxserver/couchpotato/
    - https://github.com/couchpotato/couchpotato/
    type: application
    urls:
    - couchpotato-1.0.0.tgz
    version: 1.0.0
  headphones:
  - apiVersion: v2
    appVersion: amd64-latest
    created: "2023-01-08T20:09:33.064114223+11:00"
    description: Headphones is an automatic music downloader for SABnzbd
    digest: e699a8c70853c64f7b9513947c3ec306edbc1e072b0c587bb5726cc963c0dce2
    home: https://github.com/kindred/k8s-usenet/tree/master/headphones
    icon: https://github.com/rembo10/headphones/raw/master/data/images/headphoneslogo.png
    keywords:
    - headphones
    - usenet
    - bittorrent
    name: headphones
    sources:
    - https://hub.docker.com/r/linuxserver/headphones/
    - https://github.com/rembo10/headphones
    type: application
    urls:
    - headphones-1.0.0.tgz
    version: 1.0.0
  jackett:
  - apiVersion: v2
    appVersion: amd64-latest
    created: "2023-01-08T20:09:33.065139515+11:00"
    description: API Support for your favorite torrent trackers.
    digest: 32b758efdf7822c82626f8a288cd7e351fa235f3e99cd9a5de0a0c2c831f066a
    home: https://github.com/kindred/k8s-usenet/tree/master/jackett
    keywords:
    - jackett
    - usenet
    - bittorrent
    name: jackett
    sources:
    - https://hub.docker.com/r/linuxserver/jackett/
    - https://github.com/Jackett/Jackett
    type: application
    urls:
    - jackett-1.0.0.tgz
    version: 1.0.0
  lazylibrarian:
  - apiVersion: v2
    appVersion: amd64-latest
    created: "2023-01-08T20:09:33.066231082+11:00"
    description: LazyLibrarian is a SickBeard, CouchPotato, Headphones-like application
      for ebooks, audiobooks and magazines
    digest: e57c9fe8d1134a8705fea90833f081f295e651816899a32e0c250fbe5717638e
    home: https://github.com/kindred/k8s-usenet/tree/master/lazylibrarian
    icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/lazylibrarian-icon.png
    keywords:
    - lazylibrarian
    - usenet
    - bittorrent
    name: lazylibrarian
    sources:
    - https://hub.docker.com/r/linuxserver/lazylibrarian/
    - https://gitlab.com/LazyLibrarian/LazyLibrarian
    type: application
    urls:
    - lazylibrarian-1.0.0.tgz
    version: 1.0.0
  lidarr:
  - apiVersion: v2
    appVersion: amd64-latest
    created: "2023-01-08T20:09:33.067318134+11:00"
    description: Looks and smells like Sonarr but made for music.
    digest: 87b6baddddeaa0426168dfbf3f4d5d83d531cb58db72ba694ec39809501fbc6c
    home: https://github.com/kindred/k8s-usenet/tree/master/lidarr
    icon: https://avatars1.githubusercontent.com/u/28475832?s=200&v=4
    keywords:
    - lidarr
    - usenet
    - bittorrent
    name: lidarr
    sources:
    - https://hub.docker.com/r/linuxserver/lidarr/
    - https://github.com/lidarr/Lidarr
    type: application
    urls:
    - lidarr-1.0.0.tgz
    version: 1.0.0
  medusa:
  - apiVersion: v2
    appVersion: amd64-latest
    created: "2023-01-08T20:09:33.068466609+11:00"
    description: Automatic Video Library Manager for TV Shows. It watches for new
      episodes of your favorite shows, and when they are posted it does its magic.
    digest: b5e465c97fd45d5fddbe3dceb15fdff26ddf0ea571cd16a54e64c2be6dcacbd8
    home: https://github.com/pymedusa/medusa
    icon: https://camo.githubusercontent.com/89e3583d77e019c4d77db7698c7070b684a7978a/68747470733a2f2f63646e2e7261776769742e636f6d2f70796d65647573612f6d65647573612e6769746875622e696f2f34333630643439342f696d616765732f6c6f676f2f6e65772d6c6f676f2e706e67
    keywords:
    - medusa
    - usenet
    - bittorrent
    name: medusa
    sources:
    - https://pymedusa.com/
    type: application
    urls:
    - medusa-1.0.0.tgz
    version: 1.0.0
  mylar:
  - apiVersion: v2
    appVersion: amd64-latest
    created: "2023-01-08T20:09:33.070789247+11:00"
    description: Radarr is a comic book downloading client
    digest: 2dd58e6bf479f8d97ed010fe4a8c7d5ea9063449c92fc5243e13d260284e18cf
    home: https://github.com/kindred/k8s-usenet/tree/master/mylar
    icon: https://avatars3.githubusercontent.com/u/25025331?s=400&v=4
    keywords:
    - mylar
    - usenet
    - bittorrent
    name: mylar
    sources:
    - https://hub.docker.com/r/linuxserver/mylar/
    - https://github.com/evilhero/mylar
    type: application
    urls:
    - mylar-1.0.0.tgz
    version: 1.0.0
  nzbget:
  - apiVersion: v2
    appVersion: amd64-latest
    created: "2023-01-08T20:09:33.071810054+11:00"
    description: nzbget makes Usenet as simple and streamlined as possible by automating
      everything we can.
    digest: 5c40eec2c3be5bb918a5406585e8d187aac52ab3a5a73891ad1932676d8ab29e
    home: https://nzbget.net/
    keywords:
    - nzbget
    - usenet
    - bittorrent
    name: nzbget
    sources:
    - https://hub.docker.com/r/linuxserver/nzbget/
    - https://nzbget.net/
    type: application
    urls:
    - nzbget-1.0.0.tgz
    version: 1.0.0
  nzbhydra2:
  - apiVersion: v2
    appVersion: amd64-latest
    created: "2023-01-08T20:09:33.072772006+11:00"
    description: Usenet meta search
    digest: 163111c1a64d017cb3707306244c1a569eab6dac1549150ed9b132ae53f366f2
    home: https://github.com/kindred/k8s-usenet/tree/master/nzbhydra2
    icon: https://avatars3.githubusercontent.com/u/25025331?s=400&v=4
    keywords:
    - nzbhydra2
    - usenet
    - bittorrent
    name: nzbhydra2
    sources:
    - https://hub.docker.com/r/linuxserver/nzbhydra2/
    - https://github.com/nzbhydra2/nzbhydra2/
    type: application
    urls:
    - nzbhydra2-1.0.0.tgz
    version: 1.0.0
  organizr:
  - apiVersion: v2
    appVersion: latest
    created: "2023-01-08T20:09:33.07365404+11:00"
    description: organizr is a television show downloading client
    digest: a6a339990794d3fb1b4261c81572d24591dd68251b5509d1e3b5b5ff3748f6c9
    home: https://github.com/kindred/k8s-usenet/tree/master/organizr
    icon: https://github.com/causefx/Organizr/raw/v2-develop/plugins/images/organizr/logo-wide.png
    keywords:
    - organizr
    - usenet
    - bittorrent
    name: organizr
    sources:
    - https://github.com/causefx/Organizr
    type: application
    urls:
    - organizr-1.0.0.tgz
    version: 1.0.0
  radarr:
  - apiVersion: v2
    appVersion: amd64-latest
    created: "2023-01-08T20:09:33.075705794+11:00"
    description: Radarr is a movie downloading client
    digest: ab238b450530fcd7c2bf4e727a198acad14336e4d69ccedb41f9c5e2f4fd1609
    home: https://github.com/kindred/k8s-usenet/tree/master/radarr
    icon: https://avatars3.githubusercontent.com/u/25025331?s=400&v=4
    keywords:
    - radarr
    - usenet
    - bittorrent
    name: radarr
    sources:
    - https://hub.docker.com/r/linuxserver/radarr/
    - https://github.com/Radarr/Radarr/
    type: application
    urls:
    - radarr-1.0.0.tgz
    version: 1.0.0
  sabnzbd:
  - apiVersion: v2
    appVersion: amd64-latest
    created: "2023-01-08T20:09:33.078472549+11:00"
    description: Sabnzbd makes Usenet as simple and streamlined as possible by automating
      everything we can.
    digest: a6b642cc0548f71d1d45890a62000ce6dafa360bd6ef550d4143138ea502ae6a
    home: https://sabnzbd.org/
    icon: https://sabnzbd.org/images/logo-full.svg
    keywords:
    - sabnzbd
    - usenet
    - bittorrent
    name: sabnzbd
    sources:
    - https://hub.docker.com/r/linuxserver/sabnzbd/
    - https://sabnzbd.org/
    type: application
    urls:
    - sabnzbd-1.0.0.tgz
    version: 1.0.0
  sonarr:
  - apiVersion: v2
    appVersion: amd64-latest
    created: "2023-01-08T20:09:33.079643625+11:00"
    description: Sonarr is a television show downloading client
    digest: ff5a30b2c4a370591b9ad8e472a310f1be12a5c8ac4127f4447ba5f665057b25
    home: https://github.com/kindred/k8s-usenet/tree/master/sonarr
    icon: https://avatars1.githubusercontent.com/u/1082903?s=400&v=4
    keywords:
    - sonarr
    - usenet
    - bittorrent
    name: sonarr
    sources:
    - https://hub.docker.com/r/linuxserver/sonarr/
    - https://sonarr.tv/
    type: application
    urls:
    - sonarr-1.0.0.tgz
    version: 1.0.0
  syncthing:
  - apiVersion: v2
    appVersion: amd64-latest
    created: "2023-01-08T20:09:33.080570815+11:00"
    description: Continuous file synchronization program.
    digest: cad4c9b2f5df16fa4e76841844a7a14d4db7dd4dad9075ae0ebd2af698345785
    home: https://syncthing.net/
    icon: https://syncthing.net/img/logo-horizontal.svg
    keywords:
    - syncthing
    - synchronization
    name: syncthing
    sources:
    - https://hub.docker.com/r/linuxserver/syncthing/
    - https://syncthing.net/
    type: application
    urls:
    - syncthing-1.0.0.tgz
    version: 1.0.0
  transmission:
  - apiVersion: v2
    appVersion: amd64-latest
    created: "2023-01-08T20:09:33.081702443+11:00"
    description: A fast, easy and free Bittorrent client.
    digest: b1416d6d2a9d0afd3142875a1d16cef9957797c8c7181e48f8e70edb6a444524
    home: https://transmissionbt.com/
    keywords:
    - transmission
    - bittorrent
    name: transmission
    sources:
    - https://hub.docker.com/r/linuxserver/transmission/
    - https://transmissionbt.com/
    type: application
    urls:
    - transmission-1.0.0.tgz
    version: 1.0.0
generated: "2023-01-08T20:09:33.059457648+11:00"
